
font_family     CodeNewRoman Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size	14.0

window_padding_width	4 8

background_opacity	0.8


# Neon Aether - High Contrast Cyberpunk / Genshin Theme

# Special colors
# background            #03091e
# foreground            #e0eded
# cursor                #61f2ff
# cursor_text_color     #0a0c16
# selection_background  #47a0ff
# selection_foreground  #f5f5f5

# Color table (Standard)
# color0  #454b61
# color1  #ff7164
# color2  #4ef29d
# color3  #ffcf66
# color4  #47a0ff
# color5  #ff78c7
# color6  #61f2ff
# color7  #e0eded

# Color table (Bright / High Intensity)
# color8  #7eb7a5
# color9  #ffa69e
# color10 #77ffcb
# color11 #ffe2a4
# color12 #7dc0ff
# color13 #fe96cc
# color14 #a6ffff
# color15 #ffffff


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
