
splash = false

wallpaper {
    monitor = 
#    path = /home/fer/.config/hypr/wallpapers/w-1.png
#    path = /home/fer/.config/hypr/wallpapers/w-2.png
#    path = /home/fer/.config/hypr/wallpapers/w-3.png
#    path = /home/fer/.config/hypr/wallpapers/w-1.jpg
#    path = /home/fer/.config/hypr/wallpapers/w-2.jpg
#    path = /home/fer/.config/hypr/wallpapers/w-3.jpg
#    path = /home/fer/.config/hypr/wallpapers/w-4.jpg
#    path = /home/fer/.config/hypr/wallpapers/w-5.jpeg
#    path = /home/fer/.config/hypr/wallpapers/w-6.jpg
#   path = /home/fer/.config/hypr/wallpapers/w-7.jpg
#    path = /home/fer/.config/hypr/wallpapers/w-8.jpg
    path = /home/fer/.config/hypr/wallpapers/w-9.jpg
#   path = /home/fer/.config/hypr/wallpapers/
    fit_mode = cover
#    timeout = 30
}
