

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/fer/.config/hypr/wallpapers/w-1.jpg   # Pon tu fondo aquí
#    path = /home/fer/.config/hypr/wallpapers/w-2.jpg   # Pon tu fondo aquí
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2 # 0 para que se vea nítido como antes de subir la cortina
    blur_size = 2
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# RELOJ (Estilo Windows 10)
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1.0)
    font_size = 120
    font_family = Inter Bold
    position = 0, 300
    halign = center
    valign = center
}

# FECHA
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d %B')"
    color = rgba(255, 255, 255, 1.0)
    font_size = 24
    font_family = Inter
    position = 0, 200
    halign = center
    valign = center
}

# INPUT FIELD (Caja de contraseña)
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    placeholder_text = <i>Contraseña...</i>
    hide_input = false
    position = 0, 100
    halign = center
    valign = center
}
